class WordRepository {

    constructor() {
        this._records = [
            ['any', 'qualquer'],
            ['answer', 'responder'],
            ['avocado', 'abacate'],
            ['bare', 'nu'],
            ['barn', 'celeiro'],
            ['bean', 'feijão verde'],
            ['been', 'estado'],
            ['bid', 'licitação'],
            ['bellow', 'berrar'],
            ['boilerplate', 'modelo padrão'],
            ['bookcase', 'estante de livros'],
            ['brick', 'tijolo'],
            ['catch', 'pegar'],
            ['chip', 'pedaço'],
            ['cherry', 'cereja'],
            ['cover', 'cobrir'],
            ['creep', 'rastejar'],
            ['deed', 'ato'],
            ['deep', 'profundo'],
            ['enjoy', 'apreciar'],
            ['enough', 'suficiente'],
            ['fees', 'taxas'],
            ['fetch', 'buscar'],
            ['flour', 'farinha'],
            ['fur', 'pele'],
            ['gains', 'ganhos'],
            ['glad', 'contente'],
            ['go into', 'entrar em'],
            ['goal', 'objetivo'],
            ['hiking', 'caminhada'],
            ['indoors', 'ambientes internos'],
            ['issue', 'questão'],
            ['knew', 'sabia'],
            ['laugh', 'rir'],
            ['ladder', 'escada'],
            ['leaf', 'folha'],
            ['loudly', 'em voz alta'],
            ['might', 'poderia'],
            ['nest', 'ninho'],
            ['outdoors', 'ao ar livre'],
            ['pan', 'panela'],
            ['passion fruit', 'maracujá'],
            ['pine', 'pinheiro'],
            ['pineapple', 'abacaxi'],
            ['profit', 'lucro'],
            ['pump', 'bomba'],
            ['pun', 'jogo de palavras'],
            ['pupil', 'aluno'],
            ['rescue', 'resgate'],
            ['rid', 'livrar'],
            ['sausage', 'linguiça'],
            ['settlement', 'acordo'],
            ['since', 'desde'],
            ['spark', 'faísca'],
            ['spend', 'gastar'],
            ['splash', 'espirro'],
            ['stage', 'palco'],
            ['stag', 'rapaz solteiro'],
            ['straw', 'canudo'],
            ['stub', 'comprovante'],
            ['subject', 'assunto'],
            ['sudden', 'repentino'],
            ['sunscreen', 'protetor solar'],
            ['sunny', 'ensolarado'],
            ['take a trip', 'fazer uma viagem'],
            ['tell', 'contar'],
            ['thyme', 'tomilho'],
            ['ties', 'laços'],
            ['worry', 'preocupação'],
            ['zip', 'fecho éclair']
        ];
    }

    getAll() {
        return this._records;
    }

}